### ISSUE TITLE
[BUG] MICRO_CLIENT env var is not working on client side

### ISSUE THREAD

**Issue by Dmdv** [go-micro/go-micro#2369]
I'm setting up the client. 
Client must connect to the server working via gRPC.

### Server setup

```yaml
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-server-env
data:
  MICRO_SERVER: grpc
  MICRO_REGISTRY: kubernetes
  MICRO_SERVER_NAME: micro-server
  MICRO_SERVER_VERSION: latest
```

```go
func main() {
	// Create tracer
	tracer, closer, err := jaeger.NewTracer(
		jaeger.Name(service),
		jaeger.FromEnv(true),
		jaeger.GlobalTracer(true),
	)
	if err != nil {
		log.Fatal(err)
	}

	defer func(closer io.Closer) {
		_ = closer.Close()
	}(closer)

	// Create service
	// micro.Version(version) - set version
	// micro.Name(service) - set service name
	// micro.Server(grpc.NewServer()), // must come before any other options
	srv := micro.NewService(
		micro.WrapCall(ot.NewCallWrapper(tracer)),
		micro.WrapClient(ot.NewClientWrapper(tracer)),
		micro.WrapHandler(ot.NewHandlerWrapper(tracer)),
		micro.WrapSubscriber(ot.NewSubscriberWrapper(tracer)),
	)
	srv.Init()

	// Register handler
	_ = pb.RegisterTransactionPersistenceHandler(srv.Server(), new(handler.TransactionPersistence))

	// Run service
	if err := srv.Run(); err != nil {
		log.Fatal(err)
	}
}

```

### Client setup

```yaml
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-env
data:
  MICRO_CLIENT: grpc
#  MICRO_SERVER: grpc
  MICRO_REGISTRY: kubernetes
  MICRO_SERVER_NAME: micro-server
  MICRO_SERVER_VERSION: latest

```

```go
func main() {
	// Create client
	// micro.Client(grpc.NewClient()), // must come before any other options
	// micro.Name(service), - is defined in config map
	// micro.Version(version), - is defined in config map

	srv := micro.NewService(
		micro.Client(grpc.NewClient()), // Should be working as env var: `MICRO_CLIENT: grpc` but doesn't work
		micro.Version(version),
	)
	srv.Init()

	// Create client
	c := pb.NewTransactionPersistenceService(service, srv.Client())

	for {
		// Call service
		rsp, err := c.Call(context.Background(), &pb.CallRequest{Name: "John"})
		if err != nil {
			log.Fatal(err)
		}

		log.Info(rsp)

		time.Sleep(1 * time.Second)
	}
}

```

The issue:
`MICRO_CLIENT: grpc` should replace `micro.Client(grpc.NewClient())`

When I use `micro.Client(grpc.NewClient())`, the client works fine.

```
[micro-client] 2021-11-26 18:56:55  file=micro-client/main.go:40 level=info msg:"Hello John"
[micro-client] 2021-11-26 18:56:56  file=micro-client/main.go:40 level=info msg:"Hello John"
[micro-client] 2021-11-26 18:56:57  file=micro-client/main.go:40 level=info msg:"Hello John"
[micro-client] 2021-11-26 18:56:58  file=micro-client/main.go:40 level=info msg:"Hello John"
```

But when I use `MICRO_CLIENT: grpc`, the client doesn't work.
```
  MICRO_CLIENT: grpc
  MICRO_SERVER: grpc
```

```
- deployment/micro-client: container micro-client terminated with exit code 1
    - pod/micro-client-77b5bb5b84-7fzkt: container micro-client terminated with exit code 1
      > [micro-client-77b5bb5b84-7fzkt micro-client] 2021-11-29 11:51:11  file=micro-client/main.go:36 level=fatal {"id":"go.micro.client.transport","code":500,"detail":"malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\"","status":"Internal Server Error"}
```
