### ISSUE TITLE
[BUG] Context deadline exceeded for services

### ISSUE THREAD

**Issue by shuryak** [go-micro/go-micro#2614]
I am using `go-micro` and `Docker Compose` with `NATS` and `etcd`.

Currently, I have two services: `user` and `articles`. They are successfully registered in `etcd`, as evidenced by the logs:

**`user`**:

```
2023-02-24 18:06:14  file=server/user_server.go:63 level=info Starting [service] user
2023-02-24T18:06:14.842963622Z 2023-02-24 18:06:14  file=v4@v4.9.0/service.go:96 level=info Transport [http] Listening on [::]:50051
2023-02-24T18:06:14.850933573Z 2023-02-24 18:06:14  file=v4@v4.9.0/service.go:96 level=info Broker [nats] Connected to nats://ruser:T0pS3cr3t@nats:4222
2023-02-24T18:06:14.851115257Z 2023-02-24 18:06:14  file=server/rpc_server.go:832 level=info Registry [etcd] Registering node: user-c3a98314-1bfd-4a4f-93f9-d0d6085692e4
```

**`articles`**:

```
2023-02-24 18:06:14  file=articles/main.go:57 level=info Starting [service] articles
2023-02-24T18:06:14.268090276Z 2023-02-24 18:06:14  file=v4@v4.9.0/service.go:96 level=info Transport [http] Listening on [::]:50051
2023-02-24T18:06:14.298023563Z 2023-02-24 18:06:14  file=v4@v4.9.0/service.go:96 level=info Broker [nats] Connected to nats://ruser:T0pS3cr3t@nats:4222
2023-02-24T18:06:14.298069624Z 2023-02-24 18:06:14  file=server/rpc_server.go:832 level=info Registry [etcd] Registering node: articles-f1a36482-313b-428f-a0df-05c4e9855708
```

However, I rarely have access to all my services from `go-micro-dashboard`. Most often, only one of the two services is available, sometimes both are unavailable, sometimes both are available. Here is what an unavailable service says from `go-micro-dashboard`:

```json
{
  "error": {
    "id": "go.micro.client",
    "code": 408,
    "detail": "call timeout: context deadline exceeded",
    "status": "Request Timeout"
  },
  "success": false
}
```

Previously, I used an HTTP broker, but now I am using a NATS broker. When I used an HTTP broker, the services were *more frequently unavailable*.

> When the service is unavailable, nothing happens in the logs.

It's unclear what the problem is: in the broker, in the service discovery, or somewhere else.

**The correct behavior is to have all services available at all times.**

**Comment by shuryak** [comment]
My `docker-compose.yml`:

```yaml
version: "3.9"

services:

  user-postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    container_name: user-postgres
    env_file: .env
    networks:
      - user-db-network
    volumes:
      - user-pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  articles-postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    container_name: articles-postgres
    env_file: .env
    networks:
      - articles-db-network
    volumes:
      - articles-pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  user-server:
    build:
      context: .
      dockerfile: internal/user/Dockerfile
    image: user-server
    depends_on:
      - user-postgres
      - user-db-migrations
      - etcd
      - nats
    container_name: user-server
    networks:
      - user-db-network
      - registry-network
      - broker-network
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB: ${DB}
      PG_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@user-postgres:5432/$DB?sslmode=disable
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: etcd:2379
      MICRO_SERVER_ADDRESS: :50051
      MICRO_BROKER: nats
      MICRO_BROKER_ADDRESS: ruser:T0pS3cr3t@nats
    ports:
      - "50051:50051"

  articles-server:
    build:
      context: .
      dockerfile: internal/articles/Dockerfile
    image: articles-server
    depends_on:
      - articles-postgres
      - articles-db-migrations
      - etcd
      - nats
    container_name: articles-server
    networks:
      - articles-db-network
      - registry-network
      - broker-network
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB: ${DB}
      PG_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@articles-postgres:5432/$DB?sslmode=disable
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: etcd:2379
      MICRO_SERVER_ADDRESS: :50051
      MICRO_BROKER: nats
      MICRO_BROKER_ADDRESS: ruser:T0pS3cr3t@nats
    ports:
      - "50052:50051"

  micro-dashboard:
    image: xpunch/go-micro-dashboard:latest
    environment:
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd:2379
      - MICRO_BROKER=nats
      - MICRO_BROKER_ADDRESS=ruser:T0pS3cr3t@nats
      - SERVER_ADDRESS=:8082
      - SERVER_AUTH_USERNAME=user
      - SERVER_AUTH_PASSWORD=pass
    networks:
      - registry-network
      - broker-network
    ports:
      - "8082:8082"

  etcd:
    image: bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - registry-network

  nats:
    image: nats
    networks:
      - broker-network
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"

  user-db-migrations:
    image: migrate/migrate
    container_name: user-db-migrations
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB: ${DB}
    networks:
      - user-db-network
    volumes:
      - ./internal/user/migrations:/migrations
    depends_on:
      - user-postgres
    command: -path=/migrations -database postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@user-postgres:5432/$DB?sslmode=disable up

  articles-db-migrations:
    image: migrate/migrate
    container_name: articles-db-migrations
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB: ${DB}
    networks:
      - articles-db-network
    volumes:
      - ./internal/articles/migrations:/migrations
    depends_on:
      - articles-postgres
    command: -path=/migrations -database postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@articles-postgres:5432/$DB?sslmode=disable up

volumes:
  user-pg-data:
  articles-pg-data:
networks:
  user-db-network:
  articles-db-network:
  registry-network:
  broker-network:
```
